### ISSUE TITLE
выбор карты в награду

### ISSUE THREAD

**Issue by fritzlolpro** [valigorevich/card-game-tutorial#3]
Когда игрок прошел уровень можно либо выбрать награду или закончить игру

- [x] на выбор предлагается 3 разных карты. Игрок может выбрать одну.
- [x] выбранная карта попадает в колоду
- [x] при начале следующего уровня карта находится в колоде

**Comment by valigorevich** [comment]
Я создал и подключил базовый ревард-скрин, который вызывается между волнами. Его можно использовать для выдачи наград.
Уже в мастере
